### ISSUE TITLE
Question about model size

### ISSUE THREAD

**Issue by yutongred** [GMvandeVen/class-incremental-learning#3]
Hi Gido,

Does this method have a drawback of a too large model size for large label space like ImageNet?

**Comment by GMvandeVen** [comment]
Hi, thanks for you question and interest in the code. The main point of [the paper accompanying this code](https://openaccess.thecvf.com/content/CVPR2021W/CLVision/html/van_de_Ven_Class-Incremental_Learning_With_Generative_Classifiers_CVPRW_2021_paper.html) is to put generative classification forward as a promising strategy for class-incremental learning. This strategy of generative classification does not necessarily have the drawback of leading to a too large model size for large label spaces, because the generative models for the different classes can share parts of their networks with each other. It could be argued that the specific implementation of a generative classifier that was used in this paper as a proof-of-concept, with a separate generative model per class, has this disadvantage. Although in the comparisons in the paper this was controlled for by limiting the total number of parameters. Under a limited parameter budget, having completely separate models per class is the naive solution; by sharing parts of the models it should be possible to do better.

**Comment by yutongred** [comment]
Thanks for your reply : )
